[formatter.go]
command = "gofmt"
options = ["-w"]
includes = ["*.go"]

[formatter.nix]
command = "alejandra"
includes = ["*.nix"]
excludes = ["materialized-*"]

[formatter.cue]
command = "treefmt-cue"
includes = ["*.cue"]
